### ISSUE TITLE
OnRemoval not being called in ExtendedEffects

### ISSUE THREAD

**Issue by happygill** [Tslat/TslatEffectsLib#1]
Forge 1.19.3 Mod Version-1.5

OnRemoval doesn't seem to be called when using a milk bucket or /effect clear command. The mixin for calling onRemoval is only applied to the removeEffect method in LivingEntity. 

The milk bucket seems to not call that when removing effect. It uses curePotionEffect method. The /effect clear command seems to uses removeAllEffects. Both of those method do not call removeEffect, so onRemoval is never called.

curePotionEffect below
![image](https://github.com/Tslat/TslatEffectsLib/assets/5620063/734328db-c5a7-43a0-82b4-2069975c64ad)

My current workaround is to use forge MobEffectEvent.Remove event to call onRemoval.
![image](https://github.com/Tslat/TslatEffectsLib/assets/5620063/6b4aded3-d794-43f9-b0ea-abdc9785c9f9)

**Comment by Tslat** [comment]
Stupid mojang -.-

**Comment by happygill** [comment]
Yeah,vanilla effects are poorly done, this lib definitely helps cleans some of it up.

Also I don't know if potion expire should be added to onRemoval or if that should be it's own function. 
Right now potion expiring doesn't trigger onRemoval. It would be great if you could add it to onRemoval or add a new method called onExpire to extended effects.

**Comment by Tslat** [comment]
yeah I'll check it out

**Comment by Tslat** [comment]
Fixed in 1.6
