### ISSUE TITLE
Feature Request: Persist data object stored on Mob Effect Instance

### ISSUE THREAD

**Issue by happygill** [Tslat/TslatEffectsLib#2]
Being able to setExtendedMobEffectData and getExtendedMobEffectData is very helpful for complex effects. I am not sure how implement this myself, but is there a way I can persist the data? 

Right now saving and existing the world cause the data to be set back to null. MobEffectInstance do save and load from nbt. I believe it would be very useful if you could implement a way to do it with this lib for the typeless data object.

**Comment by happygill** [comment]
I created a pull request for this. My testing so far has shown no issues with the implementation.

**Comment by Tslat** [comment]
Merged, though I have moved the _read_ hook to the HEAD rather than TAIL, so the NBT can be modified if needed before it's read by the deserializing method

Thanks for your contribution :)
