### ISSUE TITLE
Add `tick` and `canBeRemoved` methods to `ExtendedEnchantment`

### ISSUE THREAD

**Issue by thomasglasser** [Tslat/TslatEffectsLib#4]
Adding methods for when the enchantment is ticking in some `EquipmentSlot` (passed to the method, for applying effects and such) and testing whether it can be removed with a grindstone would be helpful additions to the `ExtendedEnchantment` class

**Comment by thomasglasser** [comment]
Alternative name: `canGrindstoneRemove`

**Comment by Tslat** [comment]
Done in 1.7
